In [1]:
import os
import numpy as np

def inspect_npy_files(output_dir):
    keys = ['coord', 'color', 'normal', 'segment20', 'segment200', 'instance', 'features', 'boundary']
    for key in keys:
        file_path = os.path.join(output_dir, f"{key}.npy")
        if not os.path.exists(file_path):
            print(f"{file_path} does not exist.")
            continue
        data = np.load(file_path)
        print(f"\n=== {key}.npy ===")
        print(f"Shape: {data.shape}")
        print(f"Dtype: {data.dtype}")
        print(f"Sample values:\n{data[:5]}")  # 첫 5개 행 출력

# 예시 사용법
output_dir = "/home/knuvi/Desktop/song/point/data/scannet/val/scene0011_00"  # 수정 필요
inspect_npy_files(output_dir)



=== coord.npy ===
Shape: (237360, 3)
Dtype: float32
Sample values:
[[2.5091114  0.4083811  0.14877559]
 [2.5156426  0.4059527  0.14168811]
 [2.5073788  0.4145141  0.14327997]
 [2.5004458  0.40534744 0.1462612 ]
 [2.5201747  0.47421882 0.15652634]]

=== color.npy ===
Shape: (237360, 3)
Dtype: uint8
Sample values:
[[35 33 38]
 [34 32 39]
 [40 35 43]
 [35 33 38]
 [31 30 31]]

=== normal.npy ===
Shape: (237360, 3)
Dtype: float32
Sample values:
[[ 0.19109516  0.92176497  0.3371149 ]
 [ 0.35799062  0.9311391   0.06885417]
 [ 0.59007823 -0.42843354  0.684249  ]
 [ 0.2563957   0.11805225  0.9592446 ]
 [ 0.819725   -0.5543586   0.14370042]]

=== segment20.npy ===
Shape: (237360,)
Dtype: int64
Sample values:
[14 14 14 14 14]

=== segment200.npy ===
Shape: (237360,)
Dtype: int64
Sample values:
[23 23 23 23 23]

=== instance.npy ===
Shape: (237360,)
Dtype: int64
Sample values:
[27 27 27 27 27]
/home/knuvi/Desktop/song/point/data/scannet/val/scene0011_00/features.npy does not exist.

=== boundary.

In [3]:
import numpy as np
def inspect_npy_file(npy_path, sample_size=5):
    """
    Inspect the contents of a .npy file:
    - shows data type
    - shows shape
    - prints a sample of the data
    """
    try:
        data = np.load(npy_path)
        print(f"[INFO] Loaded file: {npy_path}")
        print(f"- type: {type(data)}")
        
        if isinstance(data, np.ndarray):
            print(f"- dtype: {data.dtype}")
            print(f"- shape: {data.shape}")
            
            # Show a sample of the data
            if data.ndim == 1 or data.ndim == 2:
                print(f"- sample (first {sample_size} entries):\n{data[:sample_size]}")
            else:
                print(f"- sample (first {sample_size} elements along axis 0):\n{data[:sample_size]}")
        else:
            # in case it is something saved with allow_pickle=True
            print(f"- contents:\n{data}")
    except Exception as e:
        print(f"[ERROR] Could not read {npy_path} -> {e}")


npy_file = "/home/knuvi/Desktop/song/point/exp/scannet/scannet_tf_b-base_3dgs/result/scene0011_00_pred.npy"
inspect_npy_file(npy_file)

[INFO] Loaded file: /home/knuvi/Desktop/song/point/exp/scannet/scannet_tf_b-base_3dgs/result/scene0011_00_pred.npy
- type: <class 'numpy.ndarray'>
- dtype: int64
- shape: (237360,)
- sample (first 5 entries):
[14 14 14 14 14]
